Added a bunch more code

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,18 +1,9 @@
 #!/bin/bash
 
-#####################################
-## CONFIGURATIONS ###################
-#####################################
-ROOT_DEV=/dev/sda3
-BOOT_DEV=/dev/sda7
-KEY_DEV=/dev/sdb
-ITER_TIME=8
+# sourcing
+. ./utils
 
-#####################################
-## END OF CONFIGURATIONS ############
-#####################################
-
-# TODO: ask for user input once done debuging
+user_sure
 
 echo "WARNING: each of these locations will be wiped and data recovery"
 echo "will be very difficult: "
@@ -27,27 +18,15 @@ if [ "x$resp" != "xYES" ]; then
 fi
 
 # check for programs used in the script
-type pv >/dev/null 2>&1 || { echo >&2 "pv is not installed."; exit 1; }
-type cryptsetup >/dev/null 2>&1 || { echo >&2 "cryptsetup is not installed."; exit 1; }
-type openssl >/dev/null 2>&1 || { echo >&2 "openssl is not installed."; exit 1; }
-type xxd >/dev/null 2>&1 || { echo >&2 "xxd is not installed."; exit 1; }
-type blockdev >/dev/null 2>&1 || { echo >&2 "blockdev is not installed."; exit 1; }
+check_bins pv cryptsetup openssl xxd blockdev grub-mkconfig yes parted \
+           dd sync umount mount mkfs.ext2 grep
 
 # sanity checks
-if [ "x$(whoami)" != "xroot" ]; then
-    echo "script must be run as root."
-    exit 1
-fi
+check_root
+check_device "$ROOT_DEV"
+check_device "$BOOT_DEV"
 
-if [ ! -e "$ROOT_DEV" ]; then
-    echo "root device $ROOT_DEV does not exist."
-    exit 1
-fi
-
-if [ ! -e "$BOOT_DEV" ]; then
-    echo "boot device $BOOT_DEV does not exist."
-    exit 1
-fi
+check_debian_ready
 
 # make sure the key is a full disk
 echo $KEY_DEV | grep -q "[0-9]"
@@ -56,23 +35,7 @@ if [ $? == 0 ]; then
     exit 1
 fi
 
-# get the device sizes
-ROOT_DEV_SIZE=$(blockdev --getsize64 "$ROOT_DEV")
-BOOT_DEV_SIZE=$(blockdev --getsize64 "$BOOT_DEV")
-
 echo "removing all disks from use"
-umount_all() {
-    mount | grep "^$1[0-9]\+ " | \
-    while read line; do
-        mpoint="$(echo \"$line\" | cut -d' ' -f3)"
-        mdev="$(echo \"$line\" | cut -d' ' -f1)"
-        umount "$mpoint"
-        if [ $? != 0 ]; then
-            echo "could not umount $mdev from $mpoint."
-            exit 1
-        fi
-    done
-}
 umount_all "$KEY_DEV" && umount_all "$ROOT_DEV" && umount_all "$BOOT_DEV"
 if [ $? != 0 ]; then
     echo "could not unmount the disks from the filesystem. to avoid unexpected"
@@ -85,28 +48,39 @@ dd if=/dev/zero bs=512 count=1 of="$KEY_DEV"
 yes | parted "$KEY_DEV" mklabel msdos
 yes | parted "$KEY_DEV" unit "%" mkpart primary ext2 0 100
 
-echo "overwriting $ROOT_DEV with random data."
-#openssl enc -aes-256-cbc -iv "$(dd if=/dev/urandom bs=16 count=1 2>/dev/null | xxd -ps | tr -d '\n ')" -K "$(dd if=/dev/urandom bs=32 count=1 2>/dev/null | xxd -ps | tr -d '\n ')" </dev/zero 2>/dev/null | pv -p -s "$ROOT_DEV_SIZE" -S | dd of="$ROOT_DEV" bs=8M 2>/dev/null
+echo "overwriting $ROOT_DEV with random data"
+overwrite_device "$ROOT_DEV" "$ROOT_DEV_SIZE"
 
-echo "overwriting $BOOT_DEV with random data."
-#openssl enc -aes-256-cbc -iv "$(dd if=/dev/urandom bs=16 count=1 2>/dev/null | xxd -ps | tr -d '\n ')" -K "$(dd if=/dev/urandom bs=32 count=1 2>/dev/null | xxd -ps | tr -d '\n ')" </dev/zero 2>/dev/null | pv -p -s "$BOOT_DEV_SIZE" -S | dd of="$BOOT_DEV" bs=8M 2>/dev/null
+echo "overwriting $BOOT_DEV with random data"
+overwrite_device "$BOOT_DEV" "$BOOT_DEV_SIZE"
 
-# TODO: fix below
 echo "creating a random key"
-mkdir ./mnt
-mount $KEY_DEV ./mnt
-rm -f ./mnt/key
-dd if=/dev/urandom bs=32 count=1 of=./mnt/key
+mntdir="$(mktemp -d)"
+mount -t ext2 $KEY_DEV "$mntdir"
+if [ -e "$mntdir/key" ]; then
+    rm -f "$mntdir/key"
+fi
+dd if=/dev/urandom bs=$KEY_SIZE count=1 of="$mntdir/key"
 sync 
 
 echo "creating an encrypted volume on $ROOT_DEV"
-cryptsetup luksFormat --hash=sha256 --cipher=aes-cbc-essiv:sha256 --iter-time=$ITER_TIME "$ROOT_DEV" ./mnt/key
-cryptsetup luksOpen "$ROOT_DEV" "freshdisk" --key-file ./mnt/key
-umount ./mnt
-mkfs.ext4 /dev/mapper/freshdisk
-sync
+cryptsetup luksFormat --hash=$HASH_SPEC --cipher=$CIPHER_SPEC --iter-time=$ITER_TIME "$ROOT_DEV" "$mntdir/key"
+if [ "$?" != "0" ]; then
+    echo "error while running cryptsetup luksFormat."
+    exit 1
+fi
+freshdisk=/dev/mapper/freshdisk
+while [ -e $freshdisk ]; do
+    let "l=$RANDOM%10" 
+    freshdisk="$freshdisk$l"
+done
+cryptsetup luksOpen "$ROOT_DEV" "$freshdisk" --key-file "$mntdir/key"
+umount "$mntdir"
+mkfs.ext4 "$freshdisk"
+mount "$freshdisk" "$mntdir"
 
 echo "installing debian"
 # TODO: install debian
 
+# done
 cryptsetup luksClose "freshdisk"
